package cn.edu.service.roomService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-10-08T16:19:11.194+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "org.apache.openmeetings.webservice.RoomWebService",
                  wsdlLocation = "http://localhost:5080/openmeetings/services/RoomService?wsdl",
                  targetNamespace = "http://webservice.openmeetings.apache.org/")
public class OrgApacheOpenmeetingsWebserviceRoomWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.openmeetings.apache.org/", "org.apache.openmeetings.webservice.RoomWebService");
    public final static QName RoomWebServicePort = new QName("http://webservice.openmeetings.apache.org/", "RoomWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:5080/openmeetings/services/RoomService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrgApacheOpenmeetingsWebserviceRoomWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:5080/openmeetings/services/RoomService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrgApacheOpenmeetingsWebserviceRoomWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RoomWebService
     */
    @WebEndpoint(name = "RoomWebServicePort")
    public RoomWebService getRoomWebServicePort() {
        return super.getPort(RoomWebServicePort, RoomWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomWebService
     */
    @WebEndpoint(name = "RoomWebServicePort")
    public RoomWebService getRoomWebServicePort(WebServiceFeature... features) {
        return super.getPort(RoomWebServicePort, RoomWebService.class, features);
    }

}
